"""Hypothesis schema.

A hypothesis is an agent's interpretation of the incident — a candidate root
cause grounded in one or more signals. Hypotheses are probabilistic, unlike
signals which are deterministic facts. The aggregator ranks hypotheses from
all agents into a single ordered list.
"""

from pydantic import BaseModel, field_validator


class Hypothesis(BaseModel):
    """A candidate root cause generated by a single agent.

    Each agent may produce one or more hypotheses per run. Hypotheses must
    cite at least one signal ID — the judge rejects any that don't. The
    aggregator merges hypotheses with matching labels across agents and rewards
    cross-agent agreement with a confidence bonus.

    Attributes:
        label: Short name for the root cause (e.g. "DB Connection Pool
            Exhaustion"). Used by the aggregator for deduplication via
            case-insensitive matching.
        description: Full explanation of why this is the likely root cause,
            including how the cited signals support the conclusion.
        confidence: Agent's self-reported certainty, between 0.0 and 1.0.
            Validated at instantiation — values outside this range raise
            a ValueError immediately.
        severity: Estimated business impact — "low", "medium", or "high".
        supporting_signals: List of Signal IDs that ground this hypothesis
            (e.g. ["sig_003", "sig_006"]). Must be non-empty. The judge
            verifies each ID exists in StructuredMemory.
        contributing_agent: Name of the agent that produced this hypothesis.
            The aggregator uses this to list all agents that agreed on a
            merged hypothesis.
    """

    label: str
    description: str
    confidence: float
    severity: str
    supporting_signals: list[str]
    contributing_agent: str

    @field_validator("confidence") # before accepting this fields value, runs it through this func.
    @classmethod
    def confidence_must_be_valid(cls, v: float) -> float:
        """Enforce that confidence is a valid probability value.

        Args:
            v: The confidence value to validate.

        Returns:
            The validated confidence value, unchanged.

        Raises:
            ValueError: If v is outside the range [0.0, 1.0].
        """
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"confidence must be between 0.0 and 1.0, got {v}")
        return v
